/**
 * Competitor comparison pages (/compare/[slug]).
 * Facts about competitors come from their own public websites; `checked` is when they were last reviewed.
 * Keep them fair: say where the other product is the better choice.
 */

import type { Mark } from "@/components/comparison-mark";

/**
 * One row of a comparison table. `marks` scores each side (check, dash or cross); rows that describe
 * rather than evaluate, like "What it is", leave it out.
 */
export type ComparisonRow = { label: string; doquier: string; them: string; marks?: [Mark, Mark] };

export type Competitor = {
  slug: string;
  name: string;
  website: string;
  checked: string;
  /** One line: what the product is, in neutral terms. */
  category: string;
  /** The brand's own icon, served from /public. Until one is added, a monogram stands in. */
  icon?: string;
  /** An example video from the competitor's own showcase, shown next to one of ours. */
  clip?: { src: string; poster: string };
  /** SEO title and meta description. */
  title: string;
  description: string;
  /** Short answer shown under the H1. */
  verdict: string;
  rows: ComparisonRow[];
  chooseThem: string[];
  chooseUs: string[];
  faq: { q: string; a: string }[];
};

/** What Doquier offers, reused as the left-hand column of every comparison. */
const US = {
  model: "Done-for-you service: our team runs it end to end",
  work: "Our strategists, producers and social team",
  strategy: "Included: angles, hooks, scripts and a content calendar built around your goal",
  production: "Hundreds of videos a month across 7 formats, checked by people",
  distribution: "Optional in-market publishing and reporting, plus ad-ready files",
  languages: "8 European languages cast natively, others on request",
  pricing: "Scoped on a strategy call around your goal and volume",
  learning: "None: there's no tool to learn",
};

export const COMPETITORS: Competitor[] = [
  {
    slug: "arcads",
    icon: "/brand/competitors/arcads.jpg",
    name: "Arcads",
    website: "https://www.arcads.ai",
    checked: "September 2026",
    clip: { src: "/media/competitors/arcads.mp4", poster: "/media/posters/competitor-arcads.jpg" },
    category: "Self-serve AI video ad platform with a large library of AI actors",
    title: "Arcads alternative: Doquier vs Arcads",
    description:
      "Comparing Doquier and Arcads for AI UGC ads: self-serve tool vs done-for-you content studio. Strategy, production, languages, distribution and pricing, side by side.",
    verdict:
      "Arcads is a self-serve tool: your team writes the scripts, picks AI actors and generates the ads. Doquier is a done-for-you studio: we plan the content around your goal, produce it in bulk and can publish it for you.",
    rows: [
      { label: "What it is", doquier: US.model, them: "Self-serve platform you operate yourself" },
      { label: "Who does the work", doquier: US.work, them: "Your team", marks: ["yes", "no"] },
      {
        label: "Strategy & scripts",
        doquier: US.strategy,
        them: "You write the scripts and prompts",
        marks: ["yes", "no"],
      },
      {
        label: "Production",
        doquier: US.production,
        them: "1,000+ AI actors and several generative video models, generated by you",
        marks: ["yes", "yes"],
      },
      { label: "Publishing", doquier: US.distribution, them: "Export and upload yourself", marks: ["yes", "no"] },
      { label: "Languages", doquier: US.languages, them: "30+ languages", marks: ["yes", "yes"] },
      { label: "Learning curve", doquier: US.learning, them: "Learn the tool and its prompting", marks: ["yes", "no"] },
      { label: "Pricing", doquier: US.pricing, them: "Not published on their website; plans require an account" },
    ],
    chooseThem: [
      "You have an in-house creative strategist who writes scripts and wants hands-on control.",
      "You iterate on actor-led ad variations daily and like doing it yourself.",
      "You mainly need talking-actor ads and already have a process to test and publish them.",
    ],
    chooseUs: [
      "Nobody on your team has time to learn and run another tool.",
      "You want strategy, hooks and scripts done for you, not just the video generation.",
      "You need volume across formats: talking heads, product ads, reactions, interviews, podcasts and wall text.",
      "You're entering a European market and want native-sounding creators and in-market publishing.",
    ],
    faq: [
      {
        q: "Is Doquier an Arcads alternative?",
        a: "Yes, if you'd rather have the work done for you. Arcads gives your team a tool to generate AI actor ads; Doquier plans, produces and can publish the content, so your team only approves it.",
      },
      {
        q: "Is Doquier more expensive than Arcads?",
        a: "A self-serve subscription costs less upfront, but it doesn't include the hours of strategy, scripting, editing and publishing someone on your team still has to put in. Doquier is scoped on a strategy call around your volume, and costs up to 80% less than creator-made UGC.",
      },
      {
        q: "Can we use Arcads and Doquier together?",
        a: "Yes. Some teams keep a self-serve tool for quick in-house tests and use Doquier for the planned, high-volume programme and for new markets.",
      },
    ],
  },
  {
    slug: "heygen",
    icon: "/brand/competitors/heygen.png",
    name: "HeyGen",
    website: "https://www.heygen.com",
    checked: "September 2026",
    clip: { src: "/media/competitors/heygen.mp4", poster: "/media/posters/competitor-heygen.jpg" },
    category: "Self-serve AI avatar and video translation platform",
    title: "HeyGen alternative for UGC ads: Doquier vs HeyGen",
    description:
      "Doquier vs HeyGen: AI avatar videos you make yourself vs native-feeling UGC planned, produced and published for you. Formats, languages, workflow and pricing compared.",
    verdict:
      "HeyGen is a self-serve platform built around AI avatars, digital twins and video translation, great for presenter-led and training videos. Doquier is a done-for-you studio focused on UGC that feels native to social feeds, from plan to publishing.",
    rows: [
      { label: "What it is", doquier: US.model, them: "Self-serve AI avatar and video platform" },
      { label: "Who does the work", doquier: US.work, them: "Your team", marks: ["yes", "no"] },
      { label: "Strategy & scripts", doquier: US.strategy, them: "You write the scripts", marks: ["yes", "no"] },
      {
        label: "Production",
        doquier: US.production,
        them: "Presenter-style avatar videos, including a digital twin of you, made in their studio",
        marks: ["yes", "partial"],
      },
      { label: "Publishing", doquier: US.distribution, them: "Download and share yourself", marks: ["yes", "no"] },
      {
        label: "Languages",
        doquier: US.languages,
        them: "175+ languages and dialects, with voice cloning and lip-synced translation",
        marks: ["yes", "yes"],
      },
      {
        label: "Learning curve",
        doquier: US.learning,
        them: "Learn the studio, avatars and voices",
        marks: ["yes", "no"],
      },
      {
        label: "Pricing",
        doquier: US.pricing,
        them: "Free plan; Creator $29/mo, Pro $49/mo, Business $149/mo + $20/seat; Enterprise custom",
      },
    ],
    chooseThem: [
      "You want a digital twin of your founder or team to present videos.",
      "You make training, onboarding, sales or explainer videos rather than social ads.",
      "You need to translate existing videos into many languages quickly and cheaply.",
    ],
    chooseUs: [
      "You need ads and organic content that look like real creator UGC, not a presenter in front of a background.",
      "You want the strategy, scripts and formats decided for you, around a business goal.",
      "You need hundreds of videos a month across UGC formats, not a handful of presenter videos.",
      "You want the content published in your target markets, not just exported.",
    ],
    faq: [
      {
        q: "Is Doquier a HeyGen alternative?",
        a: "For social UGC, yes. HeyGen excels at avatar and presenter videos you make yourself; Doquier produces native-feeling UGC across formats and runs the whole programme for you.",
      },
      {
        q: "HeyGen supports more languages. Does that matter?",
        a: "It depends on the job. HeyGen's translation covers 175+ languages and dialects. Doquier covers 8 European languages with creators cast to look and sound local, plus others on request, because for ads the delivery and cultural fit matter as much as the words.",
      },
      {
        q: "Can we use HeyGen and Doquier together?",
        a: "Yes. Many teams use HeyGen for internal, training or founder-led videos and Doquier for their social UGC programme.",
      },
    ],
  },
  {
    slug: "creatify",
    icon: "/brand/competitors/creatify.png",
    name: "Creatify",
    website: "https://creatify.ai",
    checked: "September 2026",
    category: "Self-serve AI ad creation and launch platform",
    title: "Creatify alternative: Doquier vs Creatify",
    description:
      "Doquier vs Creatify for AI video ads: an ad creation and launch platform you operate vs a done-for-you UGC studio with strategy and in-market publishing. Compared side by side.",
    verdict:
      "Creatify is a self-serve platform for generating ads in bulk (URL-to-video, AI avatars, templates) and launching them to your ad accounts, with a done-for-you studio on its Enterprise plan. Doquier is a done-for-you studio by default: strategy, production and in-market publishing, run by our team.",
    rows: [
      {
        label: "What it is",
        doquier: US.model,
        them: "Self-serve ad platform; done-for-you studio on the Enterprise plan",
      },
      {
        label: "Who does the work",
        doquier: US.work,
        them: "Your team, unless you're on Enterprise",
        marks: ["yes", "partial"],
      },
      {
        label: "Strategy & scripts",
        doquier: US.strategy,
        them: "Templates, a competitor ad tracker and AI agents that your team drives",
        marks: ["yes", "partial"],
      },
      {
        label: "Production",
        doquier: US.production,
        them: "URL-to-video, AI avatars and batch generation, made by you",
        marks: ["yes", "yes"],
      },
      {
        label: "Publishing",
        doquier: US.distribution,
        them: "Launches ads to Meta, TikTok, YouTube, Snap and Amazon ad accounts",
        marks: ["yes", "partial"],
      },
      {
        label: "Languages",
        doquier: US.languages,
        them: "Multiple languages, generated in the platform",
        marks: ["yes", "yes"],
      },
      {
        label: "Learning curve",
        doquier: US.learning,
        them: "Learn the platform, agents and templates",
        marks: ["yes", "no"],
      },
      {
        label: "Pricing",
        doquier: US.pricing,
        them: "Starter $39/mo, Pro from $99/mo, Enterprise custom",
      },
    ],
    chooseThem: [
      "You run paid ads at scale and want creation, launch and testing in one tool.",
      "You have someone in-house to operate the platform every day.",
      "Your product pages are strong enough to turn straight into ads with URL-to-video.",
    ],
    chooseUs: [
      "You want the work done for you without an enterprise contract or an in-house operator.",
      "You need organic reach in a new market, not only ads launched to your ad accounts.",
      "You want people to own the strategy: angles, hooks and a calendar built around your goal.",
      "You sell in Europe and want creators cast to look and sound local in each language.",
    ],
    faq: [
      {
        q: "Is Doquier a Creatify alternative?",
        a: "Yes, if you want the full programme handled for you. Creatify gives your team a powerful platform; Doquier is the team, from content plan to production to publishing.",
      },
      {
        q: "Creatify also has a done-for-you option. What's the difference?",
        a: "Creatify offers its done-for-you studio as part of its Enterprise plan. With Doquier, done-for-you is the whole product for every client, and it includes in-market publishing and reporting, not just production.",
      },
      {
        q: "Does Doquier launch ads to our ad accounts?",
        a: "We deliver ad-ready files in every format for your media buyers, and we can publish organic content in your target markets. If you want us to work alongside your media team, we'll agree how on the strategy call.",
      },
    ],
  },
  {
    slug: "makeugc",
    icon: "/brand/competitors/makeugc.png",
    name: "MakeUGC",
    website: "https://www.makeugc.ai",
    checked: "September 2026",
    category: "Self-serve AI UGC video generator",
    title: "MakeUGC alternative: Doquier vs MakeUGC",
    description:
      "Doquier vs MakeUGC: a self-serve AI UGC generator vs a done-for-you studio that plans, produces and publishes hundreds of UGC videos a month. Features, workflow and pricing compared.",
    verdict:
      "MakeUGC is a self-serve generator for AI UGC ads, with AI actors, product-in-hand videos and templates you script yourself. Doquier is a done-for-you studio: we build the plan around your goal, produce the videos in bulk and can publish them for you.",
    rows: [
      { label: "What it is", doquier: US.model, them: "Self-serve AI UGC generator" },
      { label: "Who does the work", doquier: US.work, them: "Your team", marks: ["yes", "no"] },
      {
        label: "Strategy & scripts",
        doquier: US.strategy,
        them: "You write the scripts; templates and a video agent that recreates reference ads",
        marks: ["yes", "partial"],
      },
      {
        label: "Production",
        doquier: US.production,
        them: "1,000+ AI actors, product-in-hand videos and a built-in editor, used by you",
        marks: ["yes", "yes"],
      },
      { label: "Publishing", doquier: US.distribution, them: "Export and upload yourself", marks: ["yes", "no"] },
      { label: "Languages", doquier: US.languages, them: "50+ languages", marks: ["yes", "yes"] },
      { label: "Learning curve", doquier: US.learning, them: "Learn the generator and editor", marks: ["yes", "no"] },
      {
        label: "Pricing",
        doquier: US.pricing,
        them: "From $59/mo to $149/mo on promotional pricing; Enterprise custom",
      },
    ],
    chooseThem: [
      "You have a small budget and want to test a few product-in-hand ads yourself.",
      "You're comfortable writing scripts and editing videos in-house.",
      "You mainly need one format and don't need publishing handled.",
    ],
    chooseUs: [
      "You want a content programme, not a generator: goal, plan, production and publishing.",
      "You need several formats and languages from a single brief, every month.",
      "Your team doesn't have the hours to script, generate, review and post at volume.",
      "You're launching in a new European market and want in-market reach from day one.",
    ],
    faq: [
      {
        q: "Is Doquier a MakeUGC alternative?",
        a: "Yes, if you'd rather not run the tool yourself. MakeUGC helps your team generate AI UGC ads; Doquier plans, produces and publishes the content for you.",
      },
      {
        q: "Why would we pay for a service instead of a cheaper tool?",
        a: "The subscription is the smallest part of the cost. Someone still has to plan angles, write scripts, generate, review, edit and post every video. Doquier includes that work, and scopes it on a strategy call around your volume.",
      },
      {
        q: "Can we use MakeUGC and Doquier together?",
        a: "Yes. Some teams keep a generator for quick in-house tests while Doquier runs the planned, high-volume programme.",
      },
    ],
  },
];

/** When the comparison pages were last revised, for the sitemap. */
export const COMPARE_UPDATED = "2026-09-25";

export const getCompetitor = (slug: string) => COMPETITORS.find((c) => c.slug === slug);
